t = {
  "Language": "EN",
  "Connect Wallet": "连接钱包",
  "Your Total Rabbits": "您的所有兔币",
  "Your Total Estimated Balance Value": "您的兔币价值",
  "Usdt In Pool": "池子中的usdt",
  "Rabbits In Pool": "池子中的兔币",
  "$RABBIT Price": "兔币价格",
  "Init Supply": "初始供应量",
  "Current Supply": "现供应量",
  "Scaling Supply Rate": "伸缩供应率",
  "Staked Rate": "抵押率",
  "Unstaked Burning": "未抵押燃烧数量",
  "Total Staked": "总抵押量",
  "Burned Ratio Per Block": "每区块燃烧率",
  "Reward for Rabbit Staking": "每兔币抵押奖励数",
  "Locked Durations": "锁仓期",
  "APR": "年化率",
  "Daily ROI": "日化率",
  "Your burning $RABBIT": "您的正在燃烧的兔币量",
  "Your Staked Amount": "您已抵押的兔币量",
  "Locked until": "解仓日期",
  "Pending Rewards": "未领取奖励量",
  "Claim Rewards": "领取奖励",
  "Stake Amount": "抵押金额",
  "Withdraw Amount": "提现金额",
  "Deposit": "存入",
  "Withdraw": "提现",
  "max": "最大",
  "Reward for LP Staking": "LP抵押奖励",
  "Locked Durations of LP": "LP抵押锁仓期",
  "$LP APR": "LP抵押年化率",
  "$LP Daily ROI": "LP抵押日化率",
  "Your Protected $LP": "您的正受保护的LP量",
  "Your Staked $LP": "您的已抵押LP量",
  "Locked $LP until": "您的LP解仓日期",
  "Pending Rewards for LP": "您的抵押LP奖励量",
  "Claim Rewards for LP": "领取您的LP奖励",
  "Stake $LP Amount": "质押您的LP数量",
  "Withdraw $LP Amount": "提取您的LP数量",
  "Swap": "获取RABBIT",
  "Chart": "图表",
  "Docs": "文档",
  "Intro": "在广袤的草原上，可爱的兔子正在被不法猎人大量捕捉并杀害，导致其数量急剧减少。兔子数量以每个区块0.001%的速率在燃烧！保护你的可爱兔子不被燃烧的唯一办法就是把它们放入保护池中。<br/><br/>总共有三种类型的兔子保护池：第一种是完全保护池，把你珍爱的兔子作为流动性放入Pancake的Usdt/Rabbit兑换池中，此种保护池可免被燃烧，没有锁仓期，但是没有奖励；<br/><br/>其余两种也完全保护你的兔子并有相应奖励，每个区块总共有100个兔子繁衍奖励：大奖励池是将你在薄饼交易所里的Usdt/Rabbit的LP放入质押池中，可获得每区块奖励的80%，但是有3.5天的锁仓期；小奖励池是直接将你的兔子放到质押池中，可获得每区块总奖励的20%，此奖励池有7天的锁仓期。"
}