t = {
  "Language": "中文",
  "Connect Wallet": "Connect Wallet",
  "Your Total Rabbits": "Your Total Rabbits",
  "Your Total Estimated Balance Value": "Your Total Estimated Balance Value",
  "Usdt In Pool": "Usdt In Pool",
  "Rabbits In Pool": "Rabbits In Pool",
  "$RABBIT Price": "$RABBIT Price",
  "Init Supply": "Init Supply",
  "Current Supply": "Current Supply",
  "Scaling Supply Rate": "Scaling Supply Rate",
  "Staked Rate": "Staked Rate",
  "Unstaked Burning": "Unstaked Burning",
  "Total Staked": "Total Staked",
  "Burned Ratio Per Block": "Burned Ratio Per Block",
  "Reward for Rabbit Staking": "Reward for Rabbit Staking",
  "Locked Durations": "Locked Durations",
  "APR": "APR",
  "Daily ROI": "Daily ROI",
  "Your burning $RABBIT": "Your burning $RABBIT",
  "Your Staked Amount": "Your Staked Amount",
  "Locked until": "Locked until",
  "Pending Rewards": "Pending Rewards",
  "Claim Rewards": "Claim Rewards",
  "Stake Amount": "Stake Amount",
  "Withdraw Amount": "Withdraw Amount",
  "Approve": "Approve",
  "Deposit": "Deposit",
  "Withdraw": "Withdraw",
  "max": "max",
  "Reward for LP Staking": "Reward for LP Staking",
  "Locked Durations of LP": "Locked Durations of LP",
  "$LP APR": "$LP APR",
  "$LP Daily ROI": "$LP Daily ROI",
  "Your Protected $LP": "Your Protected $LP",
  "Your Staked $LP": "Your Staked $LP",
  "Locked $LP until": "Locked $LP until",
  "Pending Rewards for LP": "Pending Rewards for LP",
  "Claim Rewards for LP": "Claim Rewards for LP",
  "Stake $LP Amount": "Stake $LP Amount",
  "Withdraw $LP Amount": "Withdraw $LP Amount",
  "Swap": "Swap",
  "Chart": "Chart",
  "Docs": "Docs",
  "Intro": "The notorious Rabbit Cartel are running wild globally and causing a unprecedented rabbit shortage! The rabbit supply decreases rapidly with 0.001% per block... The only way to protect your rabbits is to put them in the vault.<br/>There are three types of vaults. Full protec vault will protect your precious RABBITS FULLY by adding your RABBITS as swap liquidity and it won't be affected by debase. Full protec vault has no locking period but no rewards. The other two vaults will protect your RABBITS fully in the form of rewards. The rewards are 100 RABBITS per block. Big protec vault earns you 8/10 of the rewards by staking RABBITS/USDT LP on PancakeSwap. The smol protec vault earns you only 2/10 of the rewards. Both of these vaults have a locking period of 7 days.",
  "amount should not be zero!": "amount should not be zero!",
  "program panic,please reload!": "program panic,please reload!",
  "Use Dapp to connect wallet!": "Use Dapp to connect wallet!",
  "Transaction succeed and refresh the page.": "Transaction succeed and refresh the page.",
  "Transaction failed，please try again!": "Transaction failed，please try again!",
  "Network is not BSC. Requesting to change network": "Network is not BSC. Requesting to change network",
  "Your staked Rabbit is still locked!": "Your staked Rabbit is still locked!",
  "allowance is less than the want amount": "allowance is less than the want amount",
  "user balance is less than the want amount": "user balance is less than the want amount",
  "Rabbits Per Block": "Rabbits Per Block",
  
}